### ISSUE TITLE
Decide if we want to use ElectronJS

### ISSUE THREAD

**Issue by haxoc** [cse110-fall21-group9/cse110-fa21-group9#17]
We don't know yet if we can make a website into an electron JS application. We might need to decide asap if we should be starting as an electron application

**Comment by Lord-Scrubington-II** [comment]
I have completed the prototypes for generic Electron.js deployment of a Single-Page-Application. You can find these prototypes on the github organization as a repository titled electron-test .
In general, getting an existing SPA to work in Electron is actually quite trivial. However, getting it to work such that it looks and feels native is a slightly more involved challenge. While more research is needed to determine the quirks of Electron and the new techniques that it grants us, I can rather confidently say that we should prepare for application deployment using Electron.js.

For all of our front end developers interested in JavaScript and composing web-components, I suggest looking at the resources I've linked previously, reposted here for your convenience:
Download Electron fiddle: https://www.electronjs.org/fiddle 
And also read this tutorial: https://www.electronjs.org/docs/latest/tutorial/quick-start (you don't have to do it if you're short on time, just read it; you should be able to get the gist just from the tutorial + the prototypes on the Github. If it's too confusing let me know.)
when we're making prototypes for our web components, we can try them out in electron fiddle first as a sanity check to see if they are functioning properly before integrating them into our project.
One thing that we will probably have to work on getting a little bit more comfortable with is Node.js, as several concepts/techniques from the Node runtime library are used by Electron to provide the appearance of a native application. We can read a bit more about it here: https://nodejs.dev/learn. Make sure to look at the examples using a chromium-based browser (Chrome, Edge, Opera).
