### ISSUE TITLE
Figma High Fidelity UI/UX Design

### ISSUE THREAD

**Issue by Chengjing-314** [cse110-fall21-group9/cse110-fa21-group9#6]
Please start on the UI/UX design on Figma ASAP. Reference our control flow diagrams & low-fidelity wireframes to make something final.

**Comment by Reshab18** [comment]
Finished the high-fidelity wireframes. 
Link to FIGMA: https://www.figma.com/file/JEjLCg4Ts3h1NcYJWQWJRa/WireFrames-Recipe-App?node-id=0%3A1

**Comment by Lord-Scrubington-II** [comment]
Our high-fidelity wireframes have been completed according to the latest report from our UX engineers.
